import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Yvea - CGV",
  description: "Generated by create next app",
};

export default function CgvPage() {
  return <p>CGV SAAS</p>;
}
