import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Yvea - CGU",
  description: "Generated by create next app",
};

export default function CguPage() {
  return <p>CGU</p>;
}
