import { Metadata } from "next";

import PvocHeader from "../../../_sections/_pvoc/Header/PvocHeader";
import CountriesSection from "../../../_sections/_pvoc/Countries/CountriesSection";
import RouteAProcedure from "../../../_sections/_pvoc/RouteAProcedure/RouteAProcedure";
import AnnualRegistration from "../../../_sections/_pvoc/AnnualRegistration/AnnualRegistration";

export const metadata: Metadata = {
  title: "Yvea - PVoC",
  description: "Generated by create next app",
};

import "./style.css";

export default function PvocPage() {
  return (
    <>
      <PvocHeader />
      <CountriesSection />
      <RouteAProcedure />
      <AnnualRegistration />
    </>
  );
}
