import "./globals.css";
import type { Metadata } from "next";
import { Inter, Nunito_Sans } from "next/font/google";
import Navbar from "./_components/navbar/Navbar";
import Footer from "./_components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });
const nunito_sans = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Yvea",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={nunito_sans.className}>
        <Navbar />
        <div className="main_content">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
