import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Yvea - Legal Mentions",
  description: "Generated by create next app",
};

export default function LegalMentionsPage() {
  return <p>LEGAL MENTIONS</p>;
}
